



# - name: "Ping playbook"
#   hosts: verey
#   # become: true
#   tasks:
#     - name: "Ping the server"
#       ansible.builtin.ping:


- name: "Install nginx"
  hosts: verey
  become: true
  tasks:
  - name: "Install nginx"
    ansible.builtin.package:
        name: nginx
        state: present
  - name: "Start nginx"
    ansible.builtin.service:
        name: nginx
        state: stopped

- name: intall nginx and run
  hosts: 23.22.65.170
  become: true
  tasks:
  - name: "Install nginx"
    ansible.builtin.package:
      name: nginx
      state: present
  - name: "Start nginx"
    ansible.builtin.service:
      name: nginx
      state: started